### ISSUE TITLE
cosine_similarity producing similar result values?

### ISSUE THREAD

**Issue by fossfreedom** [Polochon-street/bliss#12]
Hi,

  just running some tests - I'm using (python) cosine_similarity between two bl_song's - one is a latin track - the other is a reggae track

song3 = bl_song("/home/dad/Music/UB40 - The Very Best of UB40 1980-2000/14 - UB40 - Tell Me Is It True.ogg")
song = bl_song("/home/dad/Music/Various - Latin Fever (Disc 2)/01 - Enrique Iglesias - Bailamos (Groove Brothers Radio Edit).ogg")

print (distance.cosine_similarity(song3, song)["similarity"])
0.9550393223762512

So how should I interpret that result - are they similar?

>>> print (song["force_vector"])
{'amplitude': 5.691754341125488, 'tempo': 5.7260565757751465, 'frequency': 6.2037200927734375, 'attack': -6.0}
>>> print (song3["force_vector"])
{'amplitude': 5.661318778991699, 'tempo': 5.719758987426758, 'frequency': 2.5806758403778076, 'attack': -6.0}

**Comment by Polochon-street** [comment]
Hi,

Yes, the closer to 1 is the value, the more the songs are similar; in your case, that means the songs are highly similar.
The results may not be 100% accurate, because 2 on 4 analysis (attack and tempo) are not finished yet.
I'm seeing a signal processing expert in one or two weeks, so the results will surely improve :)

**Comment by fossfreedom** [comment]
thanks for the fast feedback.

This time I'm comparing the reggae with a very soft ballad:

>>> song4 = bl_song("/home/dad/Music/Various - Biggest & Best Ballards (disc 2)/18 - Moody Blues - Nights in White Satin.ogg")
>>> print (distance.cosine_similarity(song3, song4)["similarity"])
0.987606942653656

>>> print (song4["force_vector"]){'amplitude': 5.986419677734375, 'tempo': 5.8495001792907715, 'frequency': 4.448075771331787, 'attack': -6.0}
>>> 

Something doesnt quite feel right!  Hopefully your expert can enlighten us :)

**Comment by Polochon-street** [comment]
It seems that the « attack » field should not be the exact same for the 3 songs...
Could you send me one of these tracks, so that I can investigate?

**Comment by fossfreedom** [comment]
sure - sent one file to your email address.

**Comment by Polochon-street** [comment]
I commited a fixed version of the attack sort - you should not an 'attack' :-6, but something else (for Tell Me It's True, I have -2.876936).

I don't think I broke the python bindings this time - can you test it?

Thanks!

**Comment by fossfreedom** [comment]
hmm

Tell me its True gives me this result.

{'amplitude': 5.661318778991699, 'frequency': 2.5806758403778076, 'attack': -2.8769357204437256, 'tempo': -2.126983880996704}

however - the ballad also gives similar values:

>>> print (distance.cosine_similarity(song3, song4)["similarity"])
0.9789628982543945
>>> print (song4["force_vector"])
{'amplitude': 5.986419677734375, 'frequency': 4.448075771331787, 'attack': -2.7679076194763184, 'tempo': -2.126983880996704}
>>> 

tempo is the same now!

**Comment by Polochon-street** [comment]
I have the same result for Tell me its True.

The two real trustworthy values are « amplitude » and « frequency » - tempo results are discrete, and attack results need more work :/ .

I must say that yes, your similarity result is anormaly high - but I think all you can do is wait until I enhanced the attack and tempo treatments.

However, if you test the ballad against a metal track, it should give convincing results :p

**Comment by fossfreedom** [comment]
thanks.

Unfortunately I dont have any metal tracks to test with - however I look forward for the enhancements.

Just give me a shout and I'll test again.

**Comment by Polochon-street** [comment]
Okay - so, after investigating a bit, it seems that your files are in a floating-point format, which I totally forgot about. The decoding process is treating your float like they are int - more precisely, int32_t.

I think that's why everything is messed up. That's a progress! I'll try to get it working by tomorrow evening :)

**Comment by fossfreedom** [comment]
excellent news!

**Comment by Polochon-street** [comment]
Hi!
It took me the night, but I finally solved the issue in the [latest](https://github.com/Polochon-street/bliss/commit/4618a660a6da5f740e4ee42a3cd42aa6b6a22f1e) commit.
I now have `Similarity between ../audio/test/14 - UB40 - Tell Me Is It True.ogg and ../audio/test/18 - Moody Blues - Nights in White Satin.ogg is: 0.163254` which is, I think, rather acceptable - it's not negative (which would mean that the songs are beginning to be of a totally opposite side (like, metal/ballad)), but it's not too positive either.

What do you think of it? Does it work in your side?

**Comment by fossfreedom** [comment]
great news - I'll have a look as soon as :)

I've got a "latin" based album - from the name and the types of tracks I'm assuming the similarity figures should be fairly close i.e. close to "1".  I'll have a look together with some other tests and will report back.

I was looking at the cosine_similarity method in analyse.c but didnt see a description as to what the expected values mean - I presume return of "1" means "similar/same".

How below / above zero can values be: 1 to -1? For example - what does 0.9 mean as opposed to -0.9 ?  Is this documented in leleleplayer somewhere?

I presume 0.163 means not very similar?

N.B. I havent yet investigated what the "distance" method does - is there a doc string available to say what the various outputs are?

**Comment by Polochon-street** [comment]
Yep, that's it. 
I attached a drawing that may help you to understand the cosine similarity in this case - have a look at it!
![graph_cosine](https://cloud.githubusercontent.com/assets/9823290/11535215/31b59a18-9913-11e5-84c9-6d9ac22d4778.png)
The « distance » method is not used anymore (but it's still there for posterity): it calculates the distance between two vectors, as you would do with points on a geometric figure for instance, but it have the huge default to be absolute (the numbers can be between -infinity and +infinity - how would you know at what distance are two songs « similar » ?). Its doc is in include/bliss.h
(And yes, 0.163 means « not very similar » but the similarity is still acceptable in a way - changing from one song to another will not be that confusing, but not that smooth either.)

I hope I'm clear enough? Don't hesitate to ask more questions if you're still confused :p

**Comment by Phyks** [comment]
It is ok and can be closed then, no?

**Comment by fossfreedom** [comment]
correct!
