### ISSUE TITLE
libswresample dependency only available for very latest distros

### ISSUE THREAD

**Issue by fossfreedom** [Polochon-street/bliss#13]
my choice of development distro is ubuntu 14.04 (trusty)

Unfortunately libswresample is not a dependency available for this distro.

Also checked Debian Jessie (the latest recommended version) and it is similarly not available.

For Ubuntu 15.04 the package is called libswresample-ffmpeg-dev.

For Ubuntu 15.10 and Debian Sid libswresample-dev is available

I havent checked any other distro - I suspect most will be similarly affected.

**Comment by fossfreedom** [comment]
note - in trusty I found libavresample-dev - possibly this could be used?  A quick change in decode.c for the swresample.h declaration to avresample.h allowed some compilation but with a bunch of warnings and linking complained about swr_<functions> not available.

Note sure - I guess at some point ffmpeg deprecated libavresample for libswresample?

**Comment by Polochon-street** [comment]
Ow :/
That was a hot topic some time ago, because there was a conflict inside ffmpeg - this [link](https://en.wikipedia.org/wiki/Libav) will  explain the issue, but in short, at some point ffmpeg was divided in two « same » projects, and because Ubuntu/Debian maintainers were on the side of team that chosed to fork ffmpeg, the packages changed a little bit. Debian (and Ubuntu) are now switching back to ffmpeg, which I am using, so that's why libswresample exists only on newer Ubuntu/Debian version.

The good news is that switching from libswresample to libavresample is very easy - you just have to change swr_* prefixes by avresample_*. I'll do that tomorrow :) .
(libavresample doesn't seem to be « more deprecated » than libswresample by the way, so that's ok!)

**Comment by fossfreedom** [comment]
if its as simple as that - brilliant news.  Ta.

Also - should pkg_check_modules(MULTIMEDIA REQUIRED libavformat libavutil libavcodec)  in the CMake file have the new (or old) name as a required library?

**Comment by Polochon-street** [comment]
I have fixed it (normally) in the latest commit.
I changed the CMakeLists.txt so that you may either use libav or libsw.
Tell me if it works!

**Comment by fossfreedom** [comment]
@Polochon-street 

 excellent - there is a warning message about a "avr_ctx may be uninitialised" but that didnt stop the compilation.  Cheers.

@Phyks - with the latest changes I've applied this diff to make the python bindings to compile:

<pre>
diff --git a/python/bliss/build_bliss.py b/python/bliss/build_bliss.py
index bd815c3..72657fd 100644
--- a/python/bliss/build_bliss.py
+++ b/python/bliss/build_bliss.py
@@ -6,11 +6,11 @@ ffi.set_source("bliss._bliss",
                "#include \"bliss.h\"",
                sources=["../src/amplitude_sort.c",
                         "../src/analyze.c",
-                        "../src/decode.c",
+                        "../src/decode_av.c",
                         "../src/envelope_sort.c",
                         "../src/frequency_sort.c",
                         "../src/helpers.c"],
-               libraries=["avformat", "avutil", "avcodec"],
+               libraries=["avformat", "avutil", "avcodec", "avresample"],
                include_dirs=["/usr/include/ffmpeg/", "../include/"],
                extra_compile_args=["-std=c99"])
</pre>

Note - I'm not sure of the best way to cope with the library name change between avresample and swresample

**Comment by Phyks** [comment]
@fossfreedom Ok for the bindings. I should tweak the building process, it is not really clean at the moment. I'm quite busy at the moment, but it's on top of my TODO list and I will have a look at it ASAP!

**Comment by fossfreedom** [comment]
@Phyks 

no worries - thanks for your help!!

@Polochon-street - your changes look very good.  Have tested with a few latin songs that to me feel & sound very similar.  Your library is giving me 0.8 or better results so from an algorithm point of view I feel more confident now that this library is working quite nicely :).  

I'll crack on now and have a look at working up a rhythmbox plugin. 

cheers again!

**Comment by Phyks** [comment]
Same, I think this issue can be closed, isn't it?

**Comment by fossfreedom** [comment]
yep - good work.
