### ISSUE TITLE
ReplayGain

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#18]
Does Bliss still works if we apply ReplayGain on the files? Just wondering at the moment :)

**Comment by Polochon-street** [comment]
I think it'll work just fine, but the ReplayGain settings will not be taken in account. Could you please try and tell me, so that I can check if it works?

**Comment by Phyks** [comment]
Ok, if I have the occasion to try it, I will let you know :)

**Comment by Phyks** [comment]
I could not see any problem with it. I think it is okay and will close the issue.
