### ISSUE TITLE
ffmpeg garbage output

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#19]
Hi,

Do you think it could be possible to switch off the verbose output from ffmpeg when calling `bl_analyze`? (and eventually provide a `verbose` option to reenable it, if it can be of any use)

Thanks

**Comment by Polochon-street** [comment]
Hi,

I turned it off, as it is useless for me either; if someone is still interested in it, I'll eventually make a verbose option.

Thanks for the feedback, as always :)

**Comment by Phyks** [comment]
Thanks!
