### ISSUE TITLE
Distance choice

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#2]
Hi,

I saw that in one of the latest commits, you added some distance estimation between two songs. For this purpose, you chose to use a standard euclidian distance in 4D. 

Have you tried using a [cosine distance](https://en.wikipedia.org/wiki/Cosine_similarity)?

I think it could give better results for this purpose.

**Comment by Polochon-street** [comment]
Thanks for the suggestion!
Added it in commit 837b86456e950df8325026e29e11e26fab8a06f6 .

I'll try it in leleleplayer, and see if it gives better results.

**Comment by Phyks** [comment]
Ok, please let me know! :)
