### ISSUE TITLE
Freeing struct upon BL_UNEXPECTED

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#22]
Hi,

When an error occur in the `bl_analyze` function, one may like to recover and free the struct.

Typically,

```
if (BL_UNEXPECTED == bl_analyze(song_full_uri, &song_analysis)) {
        fprintf(stderr, "Error while parsing song: %s.\n\n", song_full_uri);
        // Free song analysis
        bl_free_song(&song_analysis);
}
```

But `bl_free_song` will fail with a segfault if the `BL_UNEXPECTED` was launch due to a file which cannot be found. So, I guess we should either distinguish two types of errors, or make `bl_free_song` safe to use on a not-allocated song? Or state it somewhere in the doc?

I may have missed something.

Thanks!

**Comment by Phyks** [comment]
Got it, actually it is that `bl_song song;` does not force the fields to have a certain value. Then, pointers are not set to `NULL`. My best bet would be to add a `bl_initialize` function to get a clean empty `bl_song` struct.

**Comment by Polochon-street** [comment]
Hi,

I added an init function in commit https://github.com/Polochon-street/bliss/commit/5c09f3a5c19e68834d7994c378edb87f0f011f15, and some error handling as well. Is that okay for you?

(And I've added a note here https://github.com/Polochon-street/bliss/commit/5c09f3a5c19e68834d7994c378edb87f0f011f15#diff-4f321c113d64f73845103ed3d1773d9dR90, what do you think?)

Thanks for the feedback!

**Comment by Phyks** [comment]
Neat! Thanks!
