### ISSUE TITLE
Wrong usage example

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#23]
Hi,

```
$ sudo make install
$ gcc -o example example.c -lbliss
```

Does not work (at least on Fedora):

```
/tmp/MPDBliss/bliss/include/bliss.h:5:34: erreur fatale : libavformat/avformat.h : Aucun fichier ou dossier de ce type
compilation terminée.
```

**Comment by Polochon-street** [comment]
My bad, you have to do
<code>gcc -o example example.c -lbliss $(pkg-config --cflags libavformat libavutil libavcodec)</code> to locate the proper header's location.

I'll edit the doc accordingly; thanks :)

**Comment by Phyks** [comment]
Thanks!
