### ISSUE TITLE
Probleme de compilation

### ISSUE THREAD

**Issue by j-k-p** [Polochon-street/bliss#26]
Bonjour
j'essaye de compiler la librairie bliss sous une ubuntu 14.04 lts
le cmake passe sans problèmes
et j'ai des erreurs
[  6%] Building C object CMakeFiles/bliss.dir/src/decode.c.o
/home/jack/bliss/src/decode.c: In function ‘bl_audio_decode’:
/home/jack/bliss/src/decode.c:15:2: error: unknown type name ‘AVCodecParameters’
  AVCodecParameters *codecpar = NULL;
  ^
/home/jack/bliss/src/decode.c:62:43: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
  codecpar = context->streams[audio_stream]->codecpar;
                                           ^
/home/jack/bliss/src/decode.c:76:30: error: request for member ‘sample_rate’ in something not a structure or union
  song->sample_rate = codecpar->sample_rate;
                              ^
/home/jack/bliss/src/decode.c:80:62: error: request for member ‘format’ in something not a structure or union
  song->nb_bytes_per_sample = av_get_bytes_per_sample(codecpar->format);
                                                              ^
/home/jack/bliss/src/decode.c:81:27: error: request for member ‘channels’ in something not a structure or union
  song->channels = codecpar->channels;
                           ^
/home/jack/bliss/src/decode.c:110:13: error: request for member ‘format’ in something not a structure or union
  if(codecpar->format != AV_SAMPLE_FMT_S16 &&
             ^
/home/jack/bliss/src/decode.c:111:11: error: request for member ‘format’ in something not a structure or union
   codecpar->format != AV_SAMPLE_FMT_S16P) {
           ^
/home/jack/bliss/src/decode.c:116:56: error: request for member ‘channel_layout’ in something not a structure or union
   av_opt_set_int(swr_ctx, "in_channel_layout", codecpar->channel_layout, 0);
                                                        ^
/home/jack/bliss/src/decode.c:118:59: error: request for member ‘format’ in something not a structure or union
   av_opt_set_sample_fmt(swr_ctx, "in_sample_fmt", codecpar->format, 0);
                                                           ^
/home/jack/bliss/src/decode.c:120:57: error: request for member ‘channel_layout’ in something not a structure or union
   av_opt_set_int(swr_ctx, "out_channel_layout", codecpar->channel_layout, 0);
                                                         ^
/home/jack/bliss/src/decode.c:192:46: error: request for member ‘format’ in something not a structure or union
  is_planar = av_sample_fmt_is_planar(codecpar->format);
                                              ^
/home/jack/bliss/src/decode.c:216:10: warning: implicit declaration of function ‘avcodec_send_packet’ [-Wimplicit-function-declaration]
    ret = avcodec_send_packet(codec_context, &avpkt);
          ^
/home/jack/bliss/src/decode.c:217:17: warning: implicit declaration of function ‘avcodec_receive_frame’ [-Wimplicit-function-declaration]
    got_frame = !avcodec_receive_frame(codec_context, decoded_frame);
                 ^
/home/jack/bliss/src/decode.c:230:14: error: request for member ‘format’ in something not a structure or union
      codecpar->format,
              ^
CMakeFiles/bliss.dir/build.make:86 : la recette pour la cible « CMakeFiles/bliss.dir/src/decode.c.o » a échouée
make[2]: *** [CMakeFiles/bliss.dir/src/decode.c.o] Erreur 1
CMakeFiles/Makefile2:104 : la recette pour la cible « CMakeFiles/bliss.dir/all » a échouée
make[1]: *** [CMakeFiles/bliss.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Merci !!!

**Comment by Polochon-street** [comment]
Bonjour,
C'est dû à un problème de version de ffmpeg ; il y a eu une petite refonte de l'API de ffmpeg il n'y a pas longtemps, et ça ne s'est pas encore répercuté dans Ubuntu 14.04 je pense.
Est-ce que remplacer
`if(AVRESAMPLE)
    add_library(bliss SHARED
    src/amplitude_sort.c
        src/decode_av.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
    src/analyze.c)
else()
    add_library(bliss SHARED
        src/amplitude_sort.c
        src/decode.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
        src/analyze.c)
endif()`
par juste
`    add_library(bliss SHARED
        src/amplitude_sort.c
        src/decode_av.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
        src/analyze.c)
` au même endroit dans le CMakeLists.txt et ensuite re-cmake puis recompiler fonctionne ?

Si non je modifierai un peu le fichier decode.c pour le rendre compatible avec les autres versions de ffmpeg :)

**Comment by j-k-p** [comment]
on progresse

Scanning dependencies of target bliss
[  6%] Building C object CMakeFiles/bliss.dir/src/amplitude_sort.c.o
[ 13%] Building C object CMakeFiles/bliss.dir/src/decode_av.c.o
[ 20%] Building C object CMakeFiles/bliss.dir/src/tempo_atk_sort.c.o
[ 26%] Building C object CMakeFiles/bliss.dir/src/frequency_sort.c.o
[ 33%] Building C object CMakeFiles/bliss.dir/src/helpers.c.o
[ 40%] Building C object CMakeFiles/bliss.dir/src/analyze.c.o
[ 46%] Linking C shared library libbliss.so
[ 46%] Built target bliss
Scanning dependencies of target detect-gapless
[ 53%] Building C object CMakeFiles/detect-gapless.dir/examples/detect-gapless.c.o
[ 60%] Linking C executable detect-gapless
libbliss.so: référence indéfinie vers « avresample_alloc_context »
libbliss.so: référence indéfinie vers « avresample_free »
libbliss.so: référence indéfinie vers « avresample_convert »
libbliss.so: référence indéfinie vers « avresample_open »
collect2: error: ld returned 1 exit status
CMakeFiles/detect-gapless.dir/build.make:95 : la recette pour la cible « detect-gapless » a échouée
make[2]: *** [detect-gapless] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/detect-gapless.dir/all » a échouée
make[1]: *** [CMakeFiles/detect-gapless.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

j'ai ajouté aussi la librairie libavresample

**Comment by Polochon-street** [comment]
Du coup je pense avoir localisé le problème ; si dans include/bliss.h tu supprimes le `#if LIBAVUTIL_VERSION_MAJOR < 54` et `#endif` et que tu réessaie cmake + compilation, est-ce que ça marche ?

Si oui, je vais update la condition pour que ça marche automatiquement, du coup !

**Comment by j-k-p** [comment]
Scanning dependencies of target bliss
[  6%] Building C object CMakeFiles/bliss.dir/src/amplitude_sort.c.o
[ 13%] Building C object CMakeFiles/bliss.dir/src/decode_av.c.o
/home/jack/bliss/src/decode_av.c: In function ‘bl_audio_decode’:
/home/jack/bliss/src/decode_av.c:205:5: warning: ‘avcodec_alloc_frame’ is deprecated [-Wdeprecated-declarations]
     decoded_frame = av_frame_alloc();
     ^
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:318:0,
                 from /home/jack/bliss/include/bliss.h:5,
                 from /home/jack/bliss/src/decode_av.c:4:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:3927:10: note: declared here
 AVFrame *avcodec_alloc_frame(void);
          ^
/home/jack/bliss/src/decode_av.c:213:5: warning: ‘avcodec_get_frame_defaults’ is deprecated [-Wdeprecated-declarations]
     av_frame_unref(decoded_frame);
     ^
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:318:0,
                 from /home/jack/bliss/include/bliss.h:5,
                 from /home/jack/bliss/src/decode_av.c:4:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:3937:6: note: declared here
 void avcodec_get_frame_defaults(AVFrame *frame);
      ^
/home/jack/bliss/src/decode_av.c:318:2: warning: ‘avcodec_get_frame_defaults’ is deprecated [-Wdeprecated-declarations]
  av_frame_unref(decoded_frame);
  ^
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:318:0,
                 from /home/jack/bliss/include/bliss.h:5,
                 from /home/jack/bliss/src/decode_av.c:4:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:3937:6: note: declared here
 void avcodec_get_frame_defaults(AVFrame *frame);
      ^
/home/jack/bliss/src/decode_av.c:320:2: warning: ‘avcodec_free_frame’ is deprecated [-Wdeprecated-declarations]
  av_frame_free(&decoded_frame);
  ^
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:318:0,
                 from /home/jack/bliss/include/bliss.h:5,
                 from /home/jack/bliss/src/decode_av.c:4:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:3952:6: note: declared here
 void avcodec_free_frame(AVFrame **frame);
      ^
[ 20%] Building C object CMakeFiles/bliss.dir/src/tempo_atk_sort.c.o
[ 26%] Building C object CMakeFiles/bliss.dir/src/frequency_sort.c.o
[ 33%] Building C object CMakeFiles/bliss.dir/src/helpers.c.o
[ 40%] Building C object CMakeFiles/bliss.dir/src/analyze.c.o
[ 46%] Linking C shared library libbliss.so
[ 46%] Built target bliss
Scanning dependencies of target detect-gapless
[ 53%] Building C object CMakeFiles/detect-gapless.dir/examples/detect-gapless.c.o
[ 60%] Linking C executable detect-gapless
libbliss.so: référence indéfinie vers « avresample_alloc_context »
libbliss.so: référence indéfinie vers « avresample_free »
libbliss.so: référence indéfinie vers « avresample_convert »
libbliss.so: référence indéfinie vers « avresample_open »
collect2: error: ld returned 1 exit status
CMakeFiles/detect-gapless.dir/build.make:95 : la recette pour la cible « detect-gapless » a échouée
make[2]: *** [detect-gapless] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/detect-gapless.dir/all » a échouée
make[1]: *** [CMakeFiles/detect-gapless.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by Polochon-street** [comment]
J'ai installé 14.04 sur une VM, et je peux compiler, donc ça doit venir d'un conflit dans tes bibliothèques installées.
Si tu reviens à la version du master de CMakeLists.txt, ton problème initial ne viendrait pas du fait que tu as une version de libswresample installée ?
Si tu enlèves toutes les références à swresample, à savoir
`pkg_check_modules(RESAMPLE QUIET libswresample)`, que tu remplaces `if(NOT RESAMPLE_FOUND)
    pkg_check_modules(RESAMPLE REQUIRED libavresample)
    set(AVRESAMPLE TRUE)
else()
    set(AVRESAMPLE FALSE)
endif()
` par `pkg_check_modules(RESAMPLE REQUIRED libavresample)
    set(AVRESAMPLE TRUE)`, est-ce que ça fonctionne ?

Si non, est-ce que tu pourrais me paster l'output de ton cmake, que je puisse voir la version de tes packages installés ?

**Comment by daedric** [comment]
J'ai l'erreur avec un 16.04, peut etre que l'auteur initial s'est trompé.
Voici les versions des packages concernes:

```Package: libavutil-dev
Version: 7:2.8.8-0ubuntu0.16.04.1
Package: libavutil-dev
Version: 7:2.8.6-1ubuntu2
Package: libavformat-dev
Version: 7:2.8.8-0ubuntu0.16.04.1
Package: libavformat-dev
Version: 7:2.8.6-1ubuntu2
Package: libavcodec-dev
Version: 7:2.8.8-0ubuntu0.16.04.1
Package: libavcodec-dev
Version: 7:2.8.6-1ubuntu2
Package: libavresample-dev
Version: 7:2.8.8-0ubuntu0.16.04.1
Package: libavresample-dev
Version: 7:2.8.6-1ubuntu2```

**Comment by j-k-p** [comment]
honte sur moi
c bien Ubuntu 16.04.1 LTS

**Comment by Polochon-street** [comment]
J'ai donc testé sur 16.04, et ça fonctionne en supprimant 
`pkg_check_modules(RESAMPLE QUIET libswresample)`,
en remplaçant
`if(NOT RESAMPLE_FOUND)
    pkg_check_modules(RESAMPLE REQUIRED libavresample)
    set(AVRESAMPLE TRUE)
else()
    set(AVRESAMPLE FALSE)
endif()
`
par
`pkg_check_modules(RESAMPLE REQUIRED libavresample)`
et enfin, remplacer 
`if(AVRESAMPLE)
    add_library(bliss SHARED
    src/amplitude_sort.c
        src/decode_av.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
    src/analyze.c)
else()
    add_library(bliss SHARED
        src/amplitude_sort.c
        src/decode.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
        src/analyze.c)
endif()`
par
` add_library(bliss SHARED
    src/amplitude_sort.c
        src/decode_av.c
        src/tempo_atk_sort.c
        src/frequency_sort.c
        src/helpers.c
    src/analyze.c)`

Ça devrait utiliser libavresample dont vous disposez, et compiler le fichier decode_av.c au lieu de decode.c (qui est moins récent)

Dites moi si ça marche, que je modifie le CMakeLists.txt en fonction :)

**Comment by j-k-p** [comment]
c bon pour moi

**Comment by daedric** [comment]
all good :)
Merci

**Comment by Polochon-street** [comment]
Corrigé dans https://github.com/Polochon-street/bliss/commit/b59026505b8fc9931a409bf831ccf4103f41524d normalement :)
