### ISSUE TITLE
use aubio for analysis?

### ISSUE THREAD

**Issue by piem** [Polochon-street/bliss#27]
hi @Polochon-street 

It would be interesting to use [aubio](https://aubio.org) to extract features from the songs to be compared.

aubio provides standard implementations of several features which are thoroughly used in academic research, and as well as in a large number of music softwares.

aubio runs on most architectures, can be built to use ffmpeg or libav, as well a fftw3, and has python bindings which are ... fast.

See also [aubio on github](https://github.com/aubio/aubio/).

cheers, piem

**Comment by Polochon-street** [comment]
Wow, I didn't know this library. That looks really useful for Bliss' purpose.

Thank you very much!

**Comment by Polochon-street** [comment]
Now using aubio in Rust bindings. Closing.
