### ISSUE TITLE
Unittests

### ISSUE THREAD

**Issue by Phyks** [Polochon-street/bliss#3]
Hi,

Could you confirm me I did not break anything with my latest pull request?

Maybe it could be useful to add some really simple unit-tests with some free of charge musics to ensure that nothing breaks in a future commit.

I am concerned by this due to the following result:
```
% ./analyze /tmp/test.mp3
[mp3 @ 0x6b5d00] Skipping 0 bytes of junk at 42438.
[mjpeg @ 0x6cfb00] Changeing bps to 8
[mp3 @ 0x6cf300] Header missing
Analysis for music /tmp/test.mp3:
Force: 0.000000
Force vector: (4.258503, 1.849175, -nan, 12.724423)
Channels: 2
Number of samples: 21309696
Sample rate: 44100
Bitrate: 254847
Number of bytes per sample: 2
Calm or loud: Unknown
Duration: 241
Artist: Phoenix
Title: Lisztomania
Album: Wolfgang Amadeus Phoenix
Track number: 1
genre: Alternative
```

`force` and `calm_or_loud` are a bit weird. The rest is ok AFAIK :)

**Comment by Polochon-street** [comment]
Hi,
Are you using the last version of the lib? I corrected a bug in frequency_sort.c this morning :)

Unit tests are a good idea, but I don't have enough time to do that... :/ . I just test the same songs over and again to see if I obtain different results.

I'll write a TODO list tomorrow with all your suggestion, so I don't forget them, thanks!

**Comment by Phyks** [comment]
If you can find relevant songs for testing, free of charge, on [Jamendo](https://www.jamendo.com/start) for example, it would be quite easy to write a few tests, just to check that the same results are obtained again and again :)

**Comment by Polochon-street** [comment]
Okay, so I asked an artist on Jamendo if I could use some of his songs (David TMX, for the record) for sample tests; while waiting for his answer, where do you think I should put the test songs? I thought of an audio/ dir at the root of the repo...

**Comment by Phyks** [comment]
I think a git versionned `audio/` folder is ok as long as there are not too many songs and they are not modified afterwards.

**Comment by Polochon-street** [comment]
Done :)

**Comment by Phyks** [comment]
Cool! I will map them to the Python bindings as well, to check that nothing is broken.

**Comment by Phyks** [comment]
Mapped onto Python bindings.
