### ISSUE TITLE
ArchLinux PKGBUILD fix please

### ISSUE THREAD

**Issue by killhellokitty** [Polochon-street/bliss#30]
In the PKGBUILD in the Dependecies list you have a "," (comma) seperating the FFMpeg dep and the cmake dep.  The "comma" needs to be removed as it forces the package to attemp to find an alternate FFMpeg that doesn't exist.  removing the "comma" fixes the issue and it accepts the default FFMpeg install.
Just a heads up, and btw nicly done!
killhellokitty-

**Comment by Polochon-street** [comment]
It's fixed!
Thanks very much for the feedback :)
