### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by mxjeff** [Polochon-street/bliss#31]
Hi,
what is the status of this project ?
Looking at the commit history it looks stall.

Cheers
k

**Comment by Polochon-street** [comment]
Hi,

The project is still open to suggestions / bugfixes / enhancements, but don't have much time to enhance it myself right now (I however use it on a daily basis).
I've made a prototype for a v2 using MATLAB as an MSc Thesis paper; the big picture would be to implement these changes (basically: add more features) in Rust, or, worst case scenario, Python :slightly_smiling_face: 

Hope it answered your question,
Polochon_street

**Comment by mxjeff** [comment]
Al right thanks for answering :)
