### ISSUE TITLE
have a bliss version api call

### ISSUE THREAD

**Issue by fossfreedom** [Polochon-street/bliss#6]
just thinking slightly ahead...

maybe a bliss version api call is needed - especially if the API evolves and future changes may break stuff.

need therefore to expose a python binding on such a call.

**Comment by Phyks** [comment]
Hmmm, not sure to understand your point :/

**Comment by fossfreedom** [comment]
something like "bliss.version()" which returns a float e.g. ("0.1")

Lets say that in a few months time bliss is at "version 0.5" - and I've designed my app to work with bliss version 0.4 or higher ... but the user has only version "0.1" installed - we need a way to say - "please install a newer version of bliss later than 0.4"

**Comment by Phyks** [comment]
Ah, I misunderstood the `version` in the title.

:+1: for this. @Polochon-street I let you implement it in the C library, and will bind it in Python.

**Comment by Polochon-street** [comment]
Hm, now I see your point @fossfreedom !
I implemented it in dc0db43 , does it look fine to you?

**Comment by fossfreedom** [comment]
Thanks ... Looks good 

The version number 0.5 does not match the readme version 0.5.1 though.

**Comment by Polochon-street** [comment]
Right. Changed!

**Comment by Phyks** [comment]
I will add them to the Python bindings tomorrow :)
