### ISSUE TITLE
python install appears not to work under Ubuntu 14.04

### ISSUE THREAD

**Issue by fossfreedom** [Polochon-street/bliss#9]
Got the following error when installing the python bindings ... note - I've had a guess here since the README appears not to have the installation instructions.

I presume python_cffi is a dependency? - or should it be python3_cffi ?

@Phyks - any thoughts?

Looking at the bottom of the trace - is this a similar issue as #8 where those libav function calls are the older names?

<pre>
dad:~/.../bliss/python$python setup.py install
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    install_requires=["cffi>=1.0.0"],
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 161, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "./bliss/build_bliss.py", line 18, in <module>
    ffi.cdef(header)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/api.py", line 107, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/cparser.py", line 243, in parse
    self._internal_parse(csource)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/cparser.py", line 251, in _internal_parse
    self._process_macros(macros)
  File "/home/dad/Downloads/bliss/python/cffi-1.3.1-py2.7-linux-x86_64.egg/cffi/cparser.py", line 327, in _process_macros
    % (key, key, key, value))
cffi.api.CDefError: only supports one of the following syntax:
  #define av_frame_unref ...     (literally dot-dot-dot)
  #define av_frame_unref NUMBER  (with NUMBER an integer constant, decimal/hex/octal)
got:
  #define av_frame_unref avcodec_get_frame_defaults
</pre>

**Comment by Phyks** [comment]
@fossfreedom Indeed, I am really sorry, I totally forgot to update the README doc… =(

So, to build them you have two solutions:
* Either `cd python; python bliss/build_bliss.py` (this will build the module in place, and you can import it then).
* Either the more standard `cd python; python setup.py install` to install the module on your system (typically in a virtualenv).

I tested it with Python3, but it should work with Python 2.7 too.

AFAIK, the only dependency is the cffi module (https://cffi.readthedocs.org/en/latest/) which **must** be installed through pip to get the latest version (> 1.0 at least, I think) to get the right API. Many distributions only ships the pre-1.0 version, which is not ok. But `setup.py` should handle this automagically through the `install_requires=["cffi>=1.0.0"]` line.


Concerning the bindings themselves, last commit from @Polochon-street broke them actually, due to me not taking into account leading "tabs" in front of pre-processor directives. I fixed them in my latest PR: https://github.com/Polochon-street/bliss/pull/10.

@Polochon-street Wouldn't it be cleaner to define `inline` functions mapping to the other ones, rather than `define` (like wrappers)? I tend to find these safer, but that's just my opinion :)

**Comment by Polochon-street** [comment]
@Phyks I'm sorry I broke your bindings without saying it in my last commit :(.
I trust you when you say `inline` functions are cleaner - cleaner than `define`, that's sure enough. However, I never used (nor knew) the `inline` keyword, so it might take a short amount of time before I implement your suggestion :)

**Comment by Phyks** [comment]
Actually, it may break again the bindings so it's ok :p

`inline` is not really important, just a bonus :)

**Comment by fossfreedom** [comment]
@Phyks - think we are making progress

with the latest stuff I'm getting the following when running `sudo python setup.py install`

basically the same as #8 - need to add somewhere -std=C99

<pre>
dad:~/.../bliss/python$sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to Bliss.egg-info/requires.txt
writing Bliss.egg-info/PKG-INFO
writing top-level names to Bliss.egg-info/top_level.txt
writing dependency_links to Bliss.egg-info/dependency_links.txt
reading manifest file 'Bliss.egg-info/SOURCES.txt'
writing manifest file 'Bliss.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/bliss._bliss.c'
already up-to-date
building 'bliss._bliss' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/bliss._bliss.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/bliss._bliss.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/amplitude_sort.c -o build/temp.linux-x86_64-2.7/../src/amplitude_sort.o
../src/amplitude_sort.c: In function ‘bl_amplitude_sort’:
../src/amplitude_sort.c:29:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < HISTOGRAM_SIZE; ++i) {
  ^
../src/amplitude_sort.c:29:2: note: use option -std=c99 or -std=gnu99 to compile your code
../src/amplitude_sort.c:44:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = start; i <= end; ++i) {
   ^
../src/amplitude_sort.c:57:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = start; i <= end; ++i) {
   ^
../src/amplitude_sort.c:68:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int g = 0; g <= N_PASSES; ++g) {
  ^
../src/amplitude_sort.c:76:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = 3; i < HISTOGRAM_SIZE - 5; ++i) {
   ^
../src/amplitude_sort.c:83:11: error: redefinition of ‘i’
   for(int i = 3; i < HISTOGRAM_SIZE - 5; ++i) {
           ^
../src/amplitude_sort.c:76:11: note: previous definition of ‘i’ was here
   for(int i = 3; i < HISTOGRAM_SIZE - 5; ++i) {
           ^
../src/amplitude_sort.c:83:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = 3; i < HISTOGRAM_SIZE - 5; ++i) {
   ^
../src/amplitude_sort.c:89:10: error: redefinition of ‘i’
  for(int i = 0; i < HISTOGRAM_SIZE; ++i) {
          ^
../src/amplitude_sort.c:29:10: note: previous definition of ‘i’ was here
  for(int i = 0; i < HISTOGRAM_SIZE; ++i) {
          ^
../src/amplitude_sort.c:89:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < HISTOGRAM_SIZE; ++i) {
  ^
../src/amplitude_sort.c:96:10: error: redefinition of ‘i’
  for(int i = INTEGRAL_INF; i <= INTEGRAL_SUP; ++i) {
          ^
../src/amplitude_sort.c:89:10: note: previous definition of ‘i’ was here
  for(int i = 0; i < HISTOGRAM_SIZE; ++i) {
          ^
../src/amplitude_sort.c:96:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = INTEGRAL_INF; i <= INTEGRAL_SUP; ++i) {
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
dad:~/.../bliss/python$
</pre>

**Comment by Phyks** [comment]
@fossfreedom Ok, try editing `python/bliss/build_bliss.py` and change the `set_source()` call.

Try adding the argument `extra_compile_args="-std=c99"` (and any other necessary flag, there is also a `extra_link_args` param if needed).

Tell me how it goes, I will update the code accordingly, as I do not have the issue here.

**Comment by fossfreedom** [comment]
@Phyks,

  more progress - thanks

<pre>
diff --git a/python/bliss/build_bliss.py b/python/bliss/build_bliss.py
index fec1b62..bd815c3 100644
--- a/python/bliss/build_bliss.py
+++ b/python/bliss/build_bliss.py
@@ -11,7 +11,8 @@ ffi.set_source("bliss._bliss",
                         "../src/frequency_sort.c",
                         "../src/helpers.c"],
                libraries=["avformat", "avutil", "avcodec"],
-               include_dirs=["/usr/include/ffmpeg/", "../include/"])
+               include_dirs=["/usr/include/ffmpeg/", "../include/"],
+               extra_compile_args=["-std=c99"])
 
 header = '\n'.join([i for i in open("../include/bliss.h", 'r').readlines()
                     if not i.strip().startswith("#")])
</pre>

this compiles and appears to install (`sudo python setup.py install`)

running `python` and then `from bliss import bl_song` gives me this:

<pre>
dad:~/Downloads$python 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bliss import bl_song
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/dad/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/bliss/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/bliss/bl_song.py", line 2, in <module>
ImportError: No module named abc
>>> 
</pre>

running `python3` and the same `from bliss import bl_song` gives me this:

<pre>
dad:~/Downloads$python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bliss import bl_song
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'bl_song'
>>> 
</pre>

`python setup.py install` output is as follows:

<pre>
dad:~/.../bliss/python$sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to Bliss.egg-info/requires.txt
writing Bliss.egg-info/PKG-INFO
writing top-level names to Bliss.egg-info/top_level.txt
writing dependency_links to Bliss.egg-info/dependency_links.txt
reading manifest file 'Bliss.egg-info/SOURCES.txt'
writing manifest file 'Bliss.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/bliss._bliss.c'
already up-to-date
building 'bliss._bliss' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/bliss._bliss.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/bliss._bliss.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/amplitude_sort.c -o build/temp.linux-x86_64-2.7/../src/amplitude_sort.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/analyze.c -o build/temp.linux-x86_64-2.7/../src/analyze.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/decode.c -o build/temp.linux-x86_64-2.7/../src/decode.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/envelope_sort.c -o build/temp.linux-x86_64-2.7/../src/envelope_sort.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/frequency_sort.c -o build/temp.linux-x86_64-2.7/../src/frequency_sort.o -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ffmpeg/ -I../include/ -I/usr/include/python2.7 -c ../src/helpers.c -o build/temp.linux-x86_64-2.7/../src/helpers.o -std=c99
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/bliss._bliss.o build/temp.linux-x86_64-2.7/../src/amplitude_sort.o build/temp.linux-x86_64-2.7/../src/analyze.o build/temp.linux-x86_64-2.7/../src/decode.o build/temp.linux-x86_64-2.7/../src/envelope_sort.o build/temp.linux-x86_64-2.7/../src/frequency_sort.o build/temp.linux-x86_64-2.7/../src/helpers.o -lavformat -lavutil -lavcodec -o build/lib.linux-x86_64-2.7/bliss/_bliss.so
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/_bliss.so -> build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/__init__.py -> build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/bl_song.py -> build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/version.py -> build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/distance.py -> build/bdist.linux-x86_64/egg/bliss
copying build/lib.linux-x86_64-2.7/bliss/build_bliss.py -> build/bdist.linux-x86_64/egg/bliss
byte-compiling build/bdist.linux-x86_64/egg/bliss/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/bliss/bl_song.py to bl_song.pyc
byte-compiling build/bdist.linux-x86_64/egg/bliss/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/bliss/distance.py to distance.pyc
byte-compiling build/bdist.linux-x86_64/egg/bliss/build_bliss.py to build_bliss.pyc
creating stub loader for bliss/_bliss.so
byte-compiling build/bdist.linux-x86_64/egg/bliss/_bliss.py to _bliss.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Bliss.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Bliss.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Bliss.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Bliss.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Bliss.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/Bliss-0.3.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Bliss-0.3.0-py2.7-linux-x86_64.egg
Removing /usr/local/lib/python2.7/dist-packages/Bliss-0.3.0-py2.7-linux-x86_64.egg
Copying Bliss-0.3.0-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Bliss 0.3.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Bliss-0.3.0-py2.7-linux-x86_64.egg
Processing dependencies for Bliss==0.3.0
Searching for cffi==1.3.1
Best match: cffi 1.3.1
Processing cffi-1.3.1-py2.7-linux-x86_64.egg
cffi 1.3.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/cffi-1.3.1-py2.7-linux-x86_64.egg
Searching for pycparser==2.14
Best match: pycparser 2.14
Processing pycparser-2.14-py2.7.egg
pycparser 2.14 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pycparser-2.14-py2.7.egg
Finished processing dependencies for Bliss==0.3.0
dad:~/.../bliss/python$
</pre>

note - running `cmake .. -DCMAKE_BUILD_TYPE=Release` as per the README installed libbliss.so installed in /usr/lib ... I was expecting /usr/local/lib - is this another issue?

<pre>
dad:~/.../bliss/build$cmake .. -DCMAKE_BUILD_TYPE=Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dad/Downloads/bliss/build
dad:~/.../bliss/build$make
Scanning dependencies of target bliss
[ 11%] Building C object CMakeFiles/bliss.dir/src/frequency_sort.c.o
Linking C shared library libbliss.so
[ 66%] Built target bliss
Linking C executable analyze
[ 77%] Built target analyze
Linking C executable distance
[ 88%] Built target distance
Linking C executable test_analyze
[100%] Built target test_analyze
dad:~/.../bliss/build$sudo make install
[ 66%] Built target bliss
[ 77%] Built target analyze
[ 88%] Built target distance
[100%] Built target test_analyze
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/libbliss.so
-- Up-to-date: /usr/include/bliss.h
dad:~/.../bliss/build$
</pre>

**Comment by Phyks** [comment]
Ok, concerning include directories, Ubuntu and other distros have a different conventions, I will update it in the next PR.

Concerning the lack of `abc`, indeed it was moved in Python 3.3 and I used this one. See https://docs.python.org/3.3/library/collections.abc.html.

I will look at it to find a way to import it. Sounds like for Python 2.7, it was in `collections.mapping`: https://docs.python.org/2.7/library/collections.html?highlight=collections#collections.Mapping. So a conditionnal import:
```
try:
    import collections.abc.Mapping as Mapping
except ImportError:
    import collections.Mapping as Mapping
```

should do the trick.


Concerning Python3, if you want to use it, you should build the module with Python3 I think (so `python3 bliss/build_bliss.py`).

Let me know how it is going.

**Comment by fossfreedom** [comment]
for rhythmbox I'm going to be using python3 ... but its good that we are debugging this to make the library useful for other python2 projects.

ok, ubuntu has v0.8.2 of the python3-cffi package.  So I ran `sudo pip install cffi` and this installed the latest 1.3 cffi stuff.

python3 bliss/build_bliss.py ran without any errors

So how do I install this python3 version of bliss - `python3 setup install` doesnt work.

**Comment by fossfreedom** [comment]
Solved!

Another for the README - for python3 you need to install the package python3-setuptools

then write `python3 setup.py install`
